"use client"

import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from '@/components/NavBar'
import { ThemeProvider } from '@emotion/react'
import { lightTheme } from '../MUITheme'
const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Course Rater',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={ inter.className }>
        <ThemeProvider theme={ lightTheme }>
          <NavBar />

          { children }

        </ThemeProvider>

      </body>
    </html>
  )
}
